// @vitest-environment node
// N1 gate: TS must verify hashes and JWTs generated by the Python backend.
// Fixture emitted by studio.security via scratchpad/gen_auth_vectors.py.
import { beforeAll, describe, expect, it } from "vitest";
import vectors from "./__fixtures__/python-auth-vectors.json";
import { verifyPassword, hashPassword } from "./password";
import { issueJwt, verifyJwt, TokenError } from "./jwt";

beforeAll(() => {
  process.env.AUTH_JWT_SECRET = vectors.secret;
});

describe("PBKDF2 cross-verification (Python → TS)", () => {
  for (const v of vectors.passwords) {
    it(`verifies Python hash for ${JSON.stringify(v.password.slice(0, 10))}…`, async () => {
      expect(await verifyPassword(v.password, v.hash, v.salt)).toBe(true);
      expect(await verifyPassword(v.password + "x", v.hash, v.salt)).toBe(false);
    });
  }

  it("TS hash with same salt reproduces the Python hash exactly", async () => {
    const v = vectors.passwords[0];
    const { hash } = await hashPassword(v.password, v.salt);
    expect(hash).toBe(v.hash);
  });
});

describe("JWT cross-verification (Python → TS)", () => {
  it("verifies a Python-issued token", async () => {
    expect(await verifyJwt(vectors.jwt_valid.token)).toBe(vectors.jwt_valid.sub);
  });

  it("rejects an expired Python-issued token", async () => {
    await expect(verifyJwt(vectors.jwt_expired)).rejects.toBeInstanceOf(TokenError);
  });

  it("rejects a tampered token", async () => {
    const tampered = vectors.jwt_valid.token.slice(0, -2) + "xx";
    await expect(verifyJwt(tampered)).rejects.toBeInstanceOf(TokenError);
  });

  it("round-trips a TS-issued token", async () => {
    expect(await verifyJwt(await issueJwt("usr-ts1"))).toBe("usr-ts1");
  });
});
