// GENERATED by backend/studio/catalog/_generate.py — do not edit by hand.
// One package per template: uniform section_schema + per-sub-cat content + per-family theme.

import re_broker_v1_schema from "./re_broker_v1/section_schema.json";
import re_broker_v1_content from "./re_broker_v1/default_content.json";
import re_broker_v1_theme from "./re_broker_v1/default_theme.json";
import re_broker_v1_registry from "./re_broker_v1/registry.json";
import re_agent_v1_schema from "./re_agent_v1/section_schema.json";
import re_agent_v1_content from "./re_agent_v1/default_content.json";
import re_agent_v1_theme from "./re_agent_v1/default_theme.json";
import re_agent_v1_registry from "./re_agent_v1/registry.json";
import re_agent_lead_v1_schema from "./re_agent_lead_v1/section_schema.json";
import re_agent_lead_v1_content from "./re_agent_lead_v1/default_content.json";
import re_agent_lead_v1_theme from "./re_agent_lead_v1/default_theme.json";
import re_agent_lead_v1_registry from "./re_agent_lead_v1/registry.json";
import re_rental_v1_schema from "./re_rental_v1/section_schema.json";
import re_rental_v1_content from "./re_rental_v1/default_content.json";
import re_rental_v1_theme from "./re_rental_v1/default_theme.json";
import re_rental_v1_registry from "./re_rental_v1/registry.json";
import re_luxury_v1_schema from "./re_luxury_v1/section_schema.json";
import re_luxury_v1_content from "./re_luxury_v1/default_content.json";
import re_luxury_v1_theme from "./re_luxury_v1/default_theme.json";
import re_luxury_v1_registry from "./re_luxury_v1/registry.json";
import ls_plumbing_v1_schema from "./ls_plumbing_v1/section_schema.json";
import ls_plumbing_v1_content from "./ls_plumbing_v1/default_content.json";
import ls_plumbing_v1_theme from "./ls_plumbing_v1/default_theme.json";
import ls_plumbing_v1_registry from "./ls_plumbing_v1/registry.json";
import ls_electrician_v1_schema from "./ls_electrician_v1/section_schema.json";
import ls_electrician_v1_content from "./ls_electrician_v1/default_content.json";
import ls_electrician_v1_theme from "./ls_electrician_v1/default_theme.json";
import ls_electrician_v1_registry from "./ls_electrician_v1/registry.json";
import electrician_v3_schema from "./electrician_v3/section_schema.json";
import electrician_v3_content from "./electrician_v3/default_content.json";
import electrician_v3_theme from "./electrician_v3/default_theme.json";
import electrician_v3_registry from "./electrician_v3/registry.json";
import ls_landscaping_v1_schema from "./ls_landscaping_v1/section_schema.json";
import ls_landscaping_v1_content from "./ls_landscaping_v1/default_content.json";
import ls_landscaping_v1_theme from "./ls_landscaping_v1/default_theme.json";
import ls_landscaping_v1_registry from "./ls_landscaping_v1/registry.json";
import ls_car_wash_v1_schema from "./ls_car_wash_v1/section_schema.json";
import ls_car_wash_v1_content from "./ls_car_wash_v1/default_content.json";
import ls_car_wash_v1_theme from "./ls_car_wash_v1/default_theme.json";
import ls_car_wash_v1_registry from "./ls_car_wash_v1/registry.json";
import ls_cleaning_v1_schema from "./ls_cleaning_v1/section_schema.json";
import ls_cleaning_v1_content from "./ls_cleaning_v1/default_content.json";
import ls_cleaning_v1_theme from "./ls_cleaning_v1/default_theme.json";
import ls_cleaning_v1_registry from "./ls_cleaning_v1/registry.json";
import ls_insurance_v1_schema from "./ls_insurance_v1/section_schema.json";
import ls_insurance_v1_content from "./ls_insurance_v1/default_content.json";
import ls_insurance_v1_theme from "./ls_insurance_v1/default_theme.json";
import ls_insurance_v1_registry from "./ls_insurance_v1/registry.json";
import rt_gift_shop_v1_schema from "./rt_gift_shop_v1/section_schema.json";
import rt_gift_shop_v1_content from "./rt_gift_shop_v1/default_content.json";
import rt_gift_shop_v1_theme from "./rt_gift_shop_v1/default_theme.json";
import rt_gift_shop_v1_registry from "./rt_gift_shop_v1/registry.json";
import rt_print_shop_v1_schema from "./rt_print_shop_v1/section_schema.json";
import rt_print_shop_v1_content from "./rt_print_shop_v1/default_content.json";
import rt_print_shop_v1_theme from "./rt_print_shop_v1/default_theme.json";
import rt_print_shop_v1_registry from "./rt_print_shop_v1/registry.json";
import rt_clothing_v1_schema from "./rt_clothing_v1/section_schema.json";
import rt_clothing_v1_content from "./rt_clothing_v1/default_content.json";
import rt_clothing_v1_theme from "./rt_clothing_v1/default_theme.json";
import rt_clothing_v1_registry from "./rt_clothing_v1/registry.json";
import rt_boutique_v1_schema from "./rt_boutique_v1/section_schema.json";
import rt_boutique_v1_content from "./rt_boutique_v1/default_content.json";
import rt_boutique_v1_theme from "./rt_boutique_v1/default_theme.json";
import rt_boutique_v1_registry from "./rt_boutique_v1/registry.json";
import rt_handmade_v1_schema from "./rt_handmade_v1/section_schema.json";
import rt_handmade_v1_content from "./rt_handmade_v1/default_content.json";
import rt_handmade_v1_theme from "./rt_handmade_v1/default_theme.json";
import rt_handmade_v1_registry from "./rt_handmade_v1/registry.json";
import ht_cafe_v1_schema from "./ht_cafe_v1/section_schema.json";
import ht_cafe_v1_content from "./ht_cafe_v1/default_content.json";
import ht_cafe_v1_theme from "./ht_cafe_v1/default_theme.json";
import ht_cafe_v1_registry from "./ht_cafe_v1/registry.json";
import ht_restaurant_v1_schema from "./ht_restaurant_v1/section_schema.json";
import ht_restaurant_v1_content from "./ht_restaurant_v1/default_content.json";
import ht_restaurant_v1_theme from "./ht_restaurant_v1/default_theme.json";
import ht_restaurant_v1_registry from "./ht_restaurant_v1/registry.json";
import ht_travel_v1_schema from "./ht_travel_v1/section_schema.json";
import ht_travel_v1_content from "./ht_travel_v1/default_content.json";
import ht_travel_v1_theme from "./ht_travel_v1/default_theme.json";
import ht_travel_v1_registry from "./ht_travel_v1/registry.json";
import he_medical_v1_schema from "./he_medical_v1/section_schema.json";
import he_medical_v1_content from "./he_medical_v1/default_content.json";
import he_medical_v1_theme from "./he_medical_v1/default_theme.json";
import he_medical_v1_registry from "./he_medical_v1/registry.json";
import he_fitness_v1_schema from "./he_fitness_v1/section_schema.json";
import he_fitness_v1_content from "./he_fitness_v1/default_content.json";
import he_fitness_v1_theme from "./he_fitness_v1/default_theme.json";
import he_fitness_v1_registry from "./he_fitness_v1/registry.json";
import he_education_v1_schema from "./he_education_v1/section_schema.json";
import he_education_v1_content from "./he_education_v1/default_content.json";
import he_education_v1_theme from "./he_education_v1/default_theme.json";
import he_education_v1_registry from "./he_education_v1/registry.json";
import pf_agency_v1_schema from "./pf_agency_v1/section_schema.json";
import pf_agency_v1_content from "./pf_agency_v1/default_content.json";
import pf_agency_v1_theme from "./pf_agency_v1/default_theme.json";
import pf_agency_v1_registry from "./pf_agency_v1/registry.json";
import pf_saas_v1_schema from "./pf_saas_v1/section_schema.json";
import pf_saas_v1_content from "./pf_saas_v1/default_content.json";
import pf_saas_v1_theme from "./pf_saas_v1/default_theme.json";
import pf_saas_v1_registry from "./pf_saas_v1/registry.json";
import pf_portfolio_v1_schema from "./pf_portfolio_v1/section_schema.json";
import pf_portfolio_v1_content from "./pf_portfolio_v1/default_content.json";
import pf_portfolio_v1_theme from "./pf_portfolio_v1/default_theme.json";
import pf_portfolio_v1_registry from "./pf_portfolio_v1/registry.json";
import gn_generic_v1_schema from "./gn_generic_v1/section_schema.json";
import gn_generic_v1_content from "./gn_generic_v1/default_content.json";
import gn_generic_v1_theme from "./gn_generic_v1/default_theme.json";
import gn_generic_v1_registry from "./gn_generic_v1/registry.json";
import pf_agency_v2_schema from "./pf_agency_v2/section_schema.json";
import pf_agency_v2_content from "./pf_agency_v2/default_content.json";
import pf_agency_v2_theme from "./pf_agency_v2/default_theme.json";
import pf_agency_v2_registry from "./pf_agency_v2/registry.json";
import ht_cafe_v2_schema from "./ht_cafe_v2/section_schema.json";
import ht_cafe_v2_content from "./ht_cafe_v2/default_content.json";
import ht_cafe_v2_theme from "./ht_cafe_v2/default_theme.json";
import ht_cafe_v2_registry from "./ht_cafe_v2/registry.json";
import he_education_v2_schema from "./he_education_v2/section_schema.json";
import he_education_v2_content from "./he_education_v2/default_content.json";
import he_education_v2_theme from "./he_education_v2/default_theme.json";
import he_education_v2_registry from "./he_education_v2/registry.json";
import he_education_v3_schema from "./he_education_v3/section_schema.json";
import he_education_v3_content from "./he_education_v3/default_content.json";
import he_education_v3_theme from "./he_education_v3/default_theme.json";
import he_education_v3_registry from "./he_education_v3/registry.json";
import he_fitness_v2_schema from "./he_fitness_v2/section_schema.json";
import he_fitness_v2_content from "./he_fitness_v2/default_content.json";
import he_fitness_v2_theme from "./he_fitness_v2/default_theme.json";
import he_fitness_v2_registry from "./he_fitness_v2/registry.json";
import gn_generic_v2_schema from "./gn_generic_v2/section_schema.json";
import gn_generic_v2_content from "./gn_generic_v2/default_content.json";
import gn_generic_v2_theme from "./gn_generic_v2/default_theme.json";
import gn_generic_v2_registry from "./gn_generic_v2/registry.json";
import gn_generic_v3_schema from "./gn_generic_v3/section_schema.json";
import gn_generic_v3_content from "./gn_generic_v3/default_content.json";
import gn_generic_v3_theme from "./gn_generic_v3/default_theme.json";
import gn_generic_v3_registry from "./gn_generic_v3/registry.json";
import he_medical_v2_schema from "./he_medical_v2/section_schema.json";
import he_medical_v2_content from "./he_medical_v2/default_content.json";
import he_medical_v2_theme from "./he_medical_v2/default_theme.json";
import he_medical_v2_registry from "./he_medical_v2/registry.json";
import pf_portfolio_v2_schema from "./pf_portfolio_v2/section_schema.json";
import pf_portfolio_v2_content from "./pf_portfolio_v2/default_content.json";
import pf_portfolio_v2_theme from "./pf_portfolio_v2/default_theme.json";
import pf_portfolio_v2_registry from "./pf_portfolio_v2/registry.json";
import pf_saas_v2_schema from "./pf_saas_v2/section_schema.json";
import pf_saas_v2_content from "./pf_saas_v2/default_content.json";
import pf_saas_v2_theme from "./pf_saas_v2/default_theme.json";
import pf_saas_v2_registry from "./pf_saas_v2/registry.json";
import rt_clothing_v2_schema from "./rt_clothing_v2/section_schema.json";
import rt_clothing_v2_content from "./rt_clothing_v2/default_content.json";
import rt_clothing_v2_theme from "./rt_clothing_v2/default_theme.json";
import rt_clothing_v2_registry from "./rt_clothing_v2/registry.json";
import ht_travel_v2_schema from "./ht_travel_v2/section_schema.json";
import ht_travel_v2_content from "./ht_travel_v2/default_content.json";
import ht_travel_v2_theme from "./ht_travel_v2/default_theme.json";
import ht_travel_v2_registry from "./ht_travel_v2/registry.json";
import ht_travel_v3_schema from "./ht_travel_v3/section_schema.json";
import ht_travel_v3_content from "./ht_travel_v3/default_content.json";
import ht_travel_v3_theme from "./ht_travel_v3/default_theme.json";
import ht_travel_v3_registry from "./ht_travel_v3/registry.json";

export const PACKAGES = {
  re_broker_v1: { schema: re_broker_v1_schema, content: re_broker_v1_content, theme: re_broker_v1_theme, registry: re_broker_v1_registry },
  re_agent_v1: { schema: re_agent_v1_schema, content: re_agent_v1_content, theme: re_agent_v1_theme, registry: re_agent_v1_registry },
  re_agent_lead_v1: { schema: re_agent_lead_v1_schema, content: re_agent_lead_v1_content, theme: re_agent_lead_v1_theme, registry: re_agent_lead_v1_registry },
  re_rental_v1: { schema: re_rental_v1_schema, content: re_rental_v1_content, theme: re_rental_v1_theme, registry: re_rental_v1_registry },
  re_luxury_v1: { schema: re_luxury_v1_schema, content: re_luxury_v1_content, theme: re_luxury_v1_theme, registry: re_luxury_v1_registry },
  ls_plumbing_v1: { schema: ls_plumbing_v1_schema, content: ls_plumbing_v1_content, theme: ls_plumbing_v1_theme, registry: ls_plumbing_v1_registry },
  ls_electrician_v1: { schema: ls_electrician_v1_schema, content: ls_electrician_v1_content, theme: ls_electrician_v1_theme, registry: ls_electrician_v1_registry },
  electrician_v3: { schema: electrician_v3_schema, content: electrician_v3_content, theme: electrician_v3_theme, registry: electrician_v3_registry },
  ls_landscaping_v1: { schema: ls_landscaping_v1_schema, content: ls_landscaping_v1_content, theme: ls_landscaping_v1_theme, registry: ls_landscaping_v1_registry },
  ls_car_wash_v1: { schema: ls_car_wash_v1_schema, content: ls_car_wash_v1_content, theme: ls_car_wash_v1_theme, registry: ls_car_wash_v1_registry },
  ls_cleaning_v1: { schema: ls_cleaning_v1_schema, content: ls_cleaning_v1_content, theme: ls_cleaning_v1_theme, registry: ls_cleaning_v1_registry },
  ls_insurance_v1: { schema: ls_insurance_v1_schema, content: ls_insurance_v1_content, theme: ls_insurance_v1_theme, registry: ls_insurance_v1_registry },
  rt_gift_shop_v1: { schema: rt_gift_shop_v1_schema, content: rt_gift_shop_v1_content, theme: rt_gift_shop_v1_theme, registry: rt_gift_shop_v1_registry },
  rt_print_shop_v1: { schema: rt_print_shop_v1_schema, content: rt_print_shop_v1_content, theme: rt_print_shop_v1_theme, registry: rt_print_shop_v1_registry },
  rt_clothing_v1: { schema: rt_clothing_v1_schema, content: rt_clothing_v1_content, theme: rt_clothing_v1_theme, registry: rt_clothing_v1_registry },
  rt_boutique_v1: { schema: rt_boutique_v1_schema, content: rt_boutique_v1_content, theme: rt_boutique_v1_theme, registry: rt_boutique_v1_registry },
  rt_handmade_v1: { schema: rt_handmade_v1_schema, content: rt_handmade_v1_content, theme: rt_handmade_v1_theme, registry: rt_handmade_v1_registry },
  ht_cafe_v1: { schema: ht_cafe_v1_schema, content: ht_cafe_v1_content, theme: ht_cafe_v1_theme, registry: ht_cafe_v1_registry },
  ht_restaurant_v1: { schema: ht_restaurant_v1_schema, content: ht_restaurant_v1_content, theme: ht_restaurant_v1_theme, registry: ht_restaurant_v1_registry },
  ht_travel_v1: { schema: ht_travel_v1_schema, content: ht_travel_v1_content, theme: ht_travel_v1_theme, registry: ht_travel_v1_registry },
  he_medical_v1: { schema: he_medical_v1_schema, content: he_medical_v1_content, theme: he_medical_v1_theme, registry: he_medical_v1_registry },
  he_fitness_v1: { schema: he_fitness_v1_schema, content: he_fitness_v1_content, theme: he_fitness_v1_theme, registry: he_fitness_v1_registry },
  he_education_v1: { schema: he_education_v1_schema, content: he_education_v1_content, theme: he_education_v1_theme, registry: he_education_v1_registry },
  pf_agency_v1: { schema: pf_agency_v1_schema, content: pf_agency_v1_content, theme: pf_agency_v1_theme, registry: pf_agency_v1_registry },
  pf_saas_v1: { schema: pf_saas_v1_schema, content: pf_saas_v1_content, theme: pf_saas_v1_theme, registry: pf_saas_v1_registry },
  pf_portfolio_v1: { schema: pf_portfolio_v1_schema, content: pf_portfolio_v1_content, theme: pf_portfolio_v1_theme, registry: pf_portfolio_v1_registry },
  gn_generic_v1: { schema: gn_generic_v1_schema, content: gn_generic_v1_content, theme: gn_generic_v1_theme, registry: gn_generic_v1_registry },
  pf_agency_v2: { schema: pf_agency_v2_schema, content: pf_agency_v2_content, theme: pf_agency_v2_theme, registry: pf_agency_v2_registry },
  ht_cafe_v2: { schema: ht_cafe_v2_schema, content: ht_cafe_v2_content, theme: ht_cafe_v2_theme, registry: ht_cafe_v2_registry },
  he_education_v2: { schema: he_education_v2_schema, content: he_education_v2_content, theme: he_education_v2_theme, registry: he_education_v2_registry },
  he_education_v3: { schema: he_education_v3_schema, content: he_education_v3_content, theme: he_education_v3_theme, registry: he_education_v3_registry },
  he_fitness_v2: { schema: he_fitness_v2_schema, content: he_fitness_v2_content, theme: he_fitness_v2_theme, registry: he_fitness_v2_registry },
  gn_generic_v2: { schema: gn_generic_v2_schema, content: gn_generic_v2_content, theme: gn_generic_v2_theme, registry: gn_generic_v2_registry },
  gn_generic_v3: { schema: gn_generic_v3_schema, content: gn_generic_v3_content, theme: gn_generic_v3_theme, registry: gn_generic_v3_registry },
  he_medical_v2: { schema: he_medical_v2_schema, content: he_medical_v2_content, theme: he_medical_v2_theme, registry: he_medical_v2_registry },
  pf_portfolio_v2: { schema: pf_portfolio_v2_schema, content: pf_portfolio_v2_content, theme: pf_portfolio_v2_theme, registry: pf_portfolio_v2_registry },
  pf_saas_v2: { schema: pf_saas_v2_schema, content: pf_saas_v2_content, theme: pf_saas_v2_theme, registry: pf_saas_v2_registry },
  rt_clothing_v2: { schema: rt_clothing_v2_schema, content: rt_clothing_v2_content, theme: rt_clothing_v2_theme, registry: rt_clothing_v2_registry },
  ht_travel_v2: { schema: ht_travel_v2_schema, content: ht_travel_v2_content, theme: ht_travel_v2_theme, registry: ht_travel_v2_registry },
  ht_travel_v3: { schema: ht_travel_v3_schema, content: ht_travel_v3_content, theme: ht_travel_v3_theme, registry: ht_travel_v3_registry },
} as const;

export type TemplateId = keyof typeof PACKAGES;
